spring.application.name=ConfigServer
server.port=9000

spring.profiles.active=native
#spring.cloud.config.server.native.search-locations=claspath:/configurations,classpath:/configurations/platform,classpath:/configurations/services
spring.cloud.config.server.native.search-locations=classpath:/configurations,classpath:/configurations/platform,classpath:/configurations/services