spring.application.name=ConfigServer
server.port=9000

spring.cloud.config.server.git.uri=https://github.com/namal1230/hospital-management-system-configurations
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.search-paths=platform,services